### PR TITLE
Database Created, Prelimary Changes For Project As Well

### PR DESCRIPTION
**Pull request by bleon-muqaj**
Worked on creating the database, I added some objects to Role. however I wanted to have access to the at least the admin panel so I can add objects that way rather than through terminal. Please review the database and the side changes I did. Change them or comment why some things may be a problem. Thanks.

### CODE REVIEW

**Review by EHBenck — APPROVED** [review]
Good work!

**Review by trex821 — COMMENTED** [review]
The models and other small changes look good. This will be good for helping me complete the course class.

**Review by youngc311 — APPROVED** [review]
Looks like good changes to me.

**Comment by mohsinshah04** [comment]
looks good

**Comment by mohsinshah04** [comment]
looks good

**Pull request merged**
